services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Updated path to the Dockerfile
    ports:
      - "3000:3000"  # Adjust the port if your app uses a different one
    environment:
      - LOCAL_MONGO_URI=mongodb://mongo:27017/mydb
    depends_on:
      - mongo
    networks:
      - local
    volumes:
      - .:/app  # Mount the current directory to /app inside the container
    command: ["ts-node", "./app.ts"]  # Command to run your application

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - local

networks:
  local:
    driver: bridge

volumes:
  mongo-data: